"""
Django settings for chupa_project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-09_+t4xr3*)syv16g_nm-57d-=kpvo!*03u=#*ve-1zr%8&n*=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

def _env_first(*keys, default=None):
    for key in keys:
        value = os.environ.get(key)
        if value:
            return value
    return default


_allowed_hosts = [
    h.strip()
    for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]
for _host in (
    'chupa-ku-chupa-production.up.railway.app',
    'chupakuchupa.up.railway.app',
    os.environ.get('RAILWAY_PUBLIC_DOMAIN', ''),
):
    if _host and _host not in _allowed_hosts:
        _allowed_hosts.append(_host)
ALLOWED_HOSTS = _allowed_hosts

_csrf_origins = [
    o.strip()
    for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]
for _host in ALLOWED_HOSTS:
    if _host not in ('localhost', '127.0.0.1'):
        _origin = f'https://{_host}'
        if _origin not in _csrf_origins:
            _csrf_origins.append(_origin)
CSRF_TRUSTED_ORIGINS = _csrf_origins


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    # 'drf_yasg',
    'corsheaders',
    # Local apps
    'accounts',
    'products',
    'orders',
    'bookings',
    'api',
]

# User uploads: local media/ in dev; Railway Bucket or S3 in production.
AWS_ACCESS_KEY_ID = _env_first('AWS_ACCESS_KEY_ID', 'ACCESS_KEY_ID', 'AWS_S3_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = _env_first(
    'AWS_SECRET_ACCESS_KEY', 'SECRET_ACCESS_KEY', 'AWS_S3_SECRET_ACCESS_KEY'
)
AWS_STORAGE_BUCKET_NAME = _env_first(
    'AWS_STORAGE_BUCKET_NAME', 'BUCKET', 'AWS_S3_BUCKET_NAME'
)
_aws_region = _env_first('AWS_S3_REGION_NAME', 'REGION', default='us-east-1')
AWS_S3_REGION_NAME = 'us-east-1' if _aws_region == 'auto' else _aws_region
AWS_S3_ENDPOINT_URL = _env_first(
    'AWS_S3_ENDPOINT_URL', 'ENDPOINT', 'AWS_ENDPOINT_URL'
)

ON_RAILWAY = bool(
    os.environ.get('RAILWAY_ENVIRONMENT_ID') or os.environ.get('RAILWAY_PUBLIC_DOMAIN')
)

USE_S3 = bool(
    AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME
)
if USE_S3:
    INSTALLED_APPS.append('storages')

AUTH_USER_MODEL = 'accounts.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

CORS_ALLOW_ALL_ORIGINS = True


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chupa_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chupa_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR}/db.sqlite3'
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
if ON_RAILWAY and not USE_S3:
    MEDIA_ROOT = Path('/tmp/chupa-media')
    MEDIA_ROOT.mkdir(parents=True, exist_ok=True)

_STATICFILES_BACKEND = 'whitenoise.storage.CompressedStaticFilesStorage'

if USE_S3:
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN') or None
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 60 * 60 * 24 * 7
    AWS_S3_SIGNATURE_VERSION = 's3v4'

    _s3_storage_options = {
        'bucket_name': AWS_STORAGE_BUCKET_NAME,
        'access_key': AWS_ACCESS_KEY_ID,
        'secret_key': AWS_SECRET_ACCESS_KEY,
        'region_name': AWS_S3_REGION_NAME,
        'signature_version': 's3v4',
        'default_acl': None,
        'querystring_auth': True,
        'querystring_expire': AWS_QUERYSTRING_EXPIRE,
        'file_overwrite': False,
    }
    if AWS_S3_ENDPOINT_URL:
        _s3_storage_options['endpoint_url'] = AWS_S3_ENDPOINT_URL

    STORAGES = {
        'default': {
            'BACKEND': 'chupa_project.storage.RailwayS3Storage',
            'OPTIONS': _s3_storage_options,
        },
        'staticfiles': {
            'BACKEND': _STATICFILES_BACKEND,
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': _STATICFILES_BACKEND,
        },
    }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
